export enum COMMON_ERRORS {
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    SERVER_ERROR = 'SERVER_ERROR',
    TOKEN_INVALID = 'TOKEN_INVALID',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
    NO_ACCESS = 'NO_ACCESS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
}

export enum CLEARANCE {
    BLOCKED = 0,
    AUTHENTICATED = 1
}

export enum TOKEN_TYPE {
    BEARER = 'Bearer',
    BASIC = 'Basic'
}