"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CLEARANCE = exports.COMMON_ERRORS = void 0;
var COMMON_ERRORS;
(function (COMMON_ERRORS) {
    COMMON_ERRORS["VALIDATION_ERROR"] = "VALIDATION_ERROR";
    COMMON_ERRORS["SERVER_ERROR"] = "SERVER_ERROR";
    COMMON_ERRORS["TOKEN_INVALID"] = "TOKEN_INVALID";
    COMMON_ERRORS["TOKEN_EXPIRED"] = "TOKEN_EXPIRED";
    COMMON_ERRORS["ROUTE_NOT_FOUND"] = "ROUTE_NOT_FOUND";
    COMMON_ERRORS["NO_ACCESS"] = "NO_ACCESS";
})(COMMON_ERRORS = exports.COMMON_ERRORS || (exports.COMMON_ERRORS = {}));
var CLEARANCE;
(function (CLEARANCE) {
    CLEARANCE[CLEARANCE["BLOCKED"] = 0] = "BLOCKED";
    CLEARANCE[CLEARANCE["AUTHENTICATED"] = 1] = "AUTHENTICATED";
})(CLEARANCE = exports.CLEARANCE || (exports.CLEARANCE = {}));
